export enum TransactionJobStatus{
    PREPARING = "PREPARING",

    ROLLABCK_WAITING = 'ROLLABCK_WAITING',
    ROLLBACKED = "ROLLBACKED",

    COMMITED_WAITING = "COMMITED_WAITING",
    COMMITED = "COMMITED",

    TIMEOUT = "TIMEOUT"
}