actors:
    -
        id: 1
        name: user
        key: asdfasdfasdf
        protocol: http
        api: 'http://127.0.0.1:8000/yimq'
        redis: master
    -
        id: 2
        name: content
        key: asdfasdfasdf
        protocol: http
        api: 'user/yimq'
        redis: db2




