actors:
    1:
        name: user
        key: asdfasdfasdf
        protocol: http
        api: 'user/yimq'
        redis: master
    2:
        name: content
        key: asdfasdfasdf
        protocol: http
        api: 'user/yimq'
        redis: db2




