

export enum TransactionJobItemStatus{
    PREPARING = 'PREPARING',
    PREPARE_FAILED = 'PREPARE_FAILED',
    PREPARE_UNKNOWN = 'PREPARE_UNKNOWN',
    PREPARED = 'PREPARED',

    CONFIRM_FAILED  = 'CONFIRM_FAILED',
    CONFIRMED = 'CONFIRMED',

    CANCEL_FAILED = 'CANCEL_FAILED',
    CANCELED = 'CANCELED'
}