

export enum TransactionJobItemStatus{
    PREPARING = 'PREPARING',
    PREPARE_FAILED = 'PREPARE_FAILED',
    PREPARE_UNKNOWN = 'PREPARE_UNKNOWN',
    PREPARED = 'PREPARED',

    CONFIRMED_FAILED  = 'CONFIRMED_FAILED',
    CONFIRMED = 'CONFIRMED',
    CANCELED = 'CANCELED'
}